# Julia 2: Iterators and Collections
### Bernt Lie
#### University of South-Eastern Norway
#### May, 2021; minor update September 2023

## Learning goals
In this session, we will look at:
* iterators
* collections

* NB: objectid

## Julia iterators
### What is an iterator?
Somewhat vaguely, we will consider an iterator as a memory-efficient way to set up an iteration of elements. As an example, consider the list of elemenents $[1,2,3,4,5,6]$ which holds $6$ elements. Thus to store this list, we would need to store 6 integers. Alternatively, we could store the first and the last element, and the fact that there is an increase of 1 between each element from the first to the last, often written as `1:1:6`. In this case, we only need to store 3 integers. With this simple iterator, we would need 3 integers no matter the number of elements in the list.

Iterators are kept *unevaluated* to save space, but are evaluated automatically upon need. There are functions for finding the first element in the iterator, to find the next element in the iterator, and to find the last element, as well as the number of elements in the iterator.

Iterators have more advanced features, but here, we don't need more features.

### Two iterators
* `start:step:stop` specifies an iterator that sets up a sequence `start,start+step,start+2*step,...,n_end` where `n_end ≤ stop` if `step` is positive, and `n_end ≥ stop` if `step` is negative. If `step` is skipped, `step` defaults to `1`.
* `range(start,stop;length)` where `start` is the start number, `stop` is the stop number, and `length` is the (optional) number of elements. The default is to select `length` so that the step-size is `1`. There is a variation `range(start,stop;step)`, but this is essentially the same as `start:step:stop`. Other variations exist.
* `first(itr)` finds the first element in iterator `itr`.
* `last(itr)` finds the last element in iterator `itr`.
* `length(itr)` finds the number of elements in iterator `itr`.

In [409]:
1:4

1:4

In [410]:
itr = -1:2:8   # Observe that the response changes this to `-1:2:7`, 
               # since `8` is not part of the iterator due to the 
               # step length `2`.

-1:2:7

In [411]:
first(itr)

-1

In [412]:
last(itr)

7

In [413]:
length(itr)

5

In [414]:
range(-1,8;step=2)

-1:2:7

In [415]:
range(0,2pi;length=10)

0.0:0.6981317007977318:6.283185307179586

In [416]:
range(0,2pi;step=0.1)

0.0:0.1:6.2

In [417]:
0:0.1:6.2

0.0:0.1:6.2

In [418]:
itr = 7:-3:-15

7:-3:-14

In [419]:
first(itr)

7

In [420]:
last(itr)

-14

In [421]:
length(itr)

8

## Collections
### Elements
Julia addresses elements of collections starting with element `1`. With collection `col`, the number of elements in the collection is found by `length(col)`. Element `n` is chosen by notation `col[n]` (assuming `n <= length(col)`). More generally, we can pick out a sequence of elements by `col[v]` where `v` is a vector (1D array) of *integers*; alternatively to a vector `v`, we can use an iterator `itr` of *integers*. We can address the *final* element of the collection by `col[end]`. The first element can also be addressed by `col[begin]`. The advantage of using `col[begin]` over `col[1]` is that there are packages (e.g., `OffsetArrays.jl`) where we can define the array index to start at other values than `1` --- `col[begin]` will still give the first element.
### Strings
Strings are a sequence of Unicode symbols enclosed in `"`. Symbol number `n` in string `str` can be chosen by the notation `str[n]`, etc. A single element of a string is a **character**, and *not* a string. **NOTE**: when the string holds non-ASCII characters, indexing may be a little strange -- Unicode characters take up more space than one byte.

Strings are immutable, which means that it is not possible to change the value of a symbol in a defined string.

In [422]:
str = "Romeo and Juliet"

"Romeo and Juliet"

In [423]:
str[1]

'R': ASCII/Unicode U+0052 (category Lu: Letter, uppercase)

In [424]:
str[1] == "R"   # a single string element is not a string

false

In [425]:
str[1] == 'R'   # the single string element is a character

true

In [426]:
"ΣaΦ"[1] == 'Σ' # Σ = `\Sigma + TAB`; Φ = `\Phi + TAB`

true

In [427]:
"ΣaΦ"[3] == 'a' # Addressing "ΣaΦ"[2] gives an error message because 
                # Unicode characters take up more space than 1 byte

true

In [428]:
length(str)

16

In [429]:
str[16], str[length(str)], str[end]

('t', 't', 't')

In [430]:
str[1:2:end]

"RmoadJle"

In [431]:
str[end:-1:1]

"teiluJ dna oemoR"

In [432]:
str[1] = "G"    # This gives an error since strings are immutable, and 
                # it is not possible to change an element in a defined 
                # string. `str[1] = 'G'` also fails.

MethodError: MethodError: no method matching setindex!(::String, ::String, ::Int64)

In [433]:
sizeof(""), sizeof(" "),sizeof(str)

(0, 1, 16)

### String functions
* `str1 * str2` concatenates the two strings. *Note*: some other programming languages uses `+` for concatenation, but Julia uses `*`.
* `str^n` repeats the symbols in `str` a number of `n` times. Alternative syntax: `repeat(str,n)`
* `string(x1,...,xn)` creates a string by converting each element `x1,...,xn` to strings and concatenating them.
* `println(str)` prints the string (minus the quotation brackets) to the output cell, followed by linefeed. `print(str)` prints the string *without* linefeed.
* Interpolation/substitution: symbol `$` is used for inserting the value of an identifier or an expression which is evaluated, into a string. Examples: `$var`, `$(var)`, `$(1+2)`. The use of `$` for interpolation in Julia implies that extra care must be used when describing, e.g., $\LaTeX$ code in strings.

Many more functions exist, e.g., support for inserting layout specification for interpolated numbers.

In [434]:
str1 = "Romeo"
str2 = "and"
str3 = "Juliet"
str1*str2*str3, str1*" "*str2*" "*str3

("RomeoandJuliet", "Romeo and Juliet")

In [435]:
str = "abc"
str^3, repeat(str,3)

("abcabcabc", "abcabcabc")

In [436]:
string(str,1,false,1.2e3,pi)

"abc1false1200.0π"

In [437]:
println(str)

abc


In [438]:
x = 1e3
println("The result is x = $x")

The result is x = 1000.0


In [439]:
println("The result is y = $(1+10/x)")

The result is y = 1.01


### Converting strings to numbers
Sometimes, numbers may be provided as strings, e.g., when reading data from files.
* `parse(Type, string; base)` converts a number provided as `string` into a number of `Type`, where the number in the string optionally is taken to be of base set equal to `base`.

In [440]:
parse(Int,"125")

125

In [441]:
parse(Int,"125";base=6)

53

In [442]:
parse(Int,"af3";base=16)

2803

In [443]:
parse(Float64,"125")

125.0

In [444]:
parse(Float64,"1e3")

1000.0

In [445]:
parse(Float32,"1e3")

1000.0f0

### Specialized strings
A number of specialized strings exist, which are denoted by an identifier *prepending* the string. Examples are *raw strings*, which are denoted by `raw"..."` where `...` is some string, e.g., `raw"Raw string content \$"`, *regular expression strings*  denoted by `r"..."`, *color specification strings* using Julia package `Colors.jl` denoted by `colorant"..."`, $\LaTeX$ *code strings* using Julia package `LaTeXStrings.jl` denoted by `L"..."`, etc. We will meet some of these specialized strings later in this introduction.

### Symbols
Symbols are created by instantiator `Symbol(str)`, where `str` is a string that contains the description of the symbol.

If the content of the string is a valid Julia identifier `identifier`, the symbol is *presented* as a so-called "unevaluated" identifier; `Symbol("identifier")` leads to `:identifier`.

In [446]:
Symbol("mass [kg]")

Symbol("mass [kg]")

In [447]:
Symbol("red")

:red

### Unevaluated expressions
* **Definition**: `:(expression)` creates an unevaluated version of a valid Julia `expression`. For the specific case that `expression` is a valid Julia identifier, the unevaluated identifier is the same as the *symbol* of the identifier; see Symbols
* **Evaluation** `eval(expr)` where `expr` is an expression. 

Operations on unevaluated Julia expressions is of key importance in *macros* and other transformations of Julia code.

In [448]:
:red

:red

In [449]:
x=3

3

In [450]:
:x, eval(:x)

(:x, 3)

In [451]:
y = :(x+3^2)

:(x + 3 ^ 2)

In [452]:
eval(y)

12

### Tuples
A tuple is a data structure closely related to function arguments and return values from functions. A tuple is a fixed-length container that can hold any values, but cannot be modified (it is *immutable*). Tuples are constructed with commas and parentheses, and can be accessed via indexing using `itr` or lists of integers.

Length one tuples (singletons) must be written with a comma at the end.

In [453]:
1,2    # This returns a tuple even though there is no parenthesis around it

(1, 2)

In [454]:
(1,)        # This returns a tuple  -- singletons *must* use parenthesis, 
            # i.e., `1,` does not work

(1,)

In [455]:
t1 = (1,2,3)

(1, 2, 3)

In [456]:
sizeof(t1), length(t1)

(24, 3)

In [457]:
t1[1:2]

(1, 2)

In [602]:
t1[3] = 4    # Doesn't work because tuples are immutable

MethodError: MethodError: no method matching setindex!(::Tuple{Int64, Int64, Int64}, ::Int64, ::Int64)

In [603]:
t2 = ((2,3),(:red,:green,:blue))

((2, 3), (:red, :green, :blue))

In [616]:
sizeof(t2), length(t2)

(24, 3)

### Named tuples
Tuple elements can optionally be named so they can be addressed using the name instead of the position.

In [617]:
t3 = (p = 1, v = 0.2, T = 273)  # E.g., `p` is pressure, `v` is molar volume, 
                                # `T` is absolute temperature

(p = 1, v = 0.2, T = 273)

In [618]:
t3.T == t3[3]

true

In [619]:
t4 = (pos = (2,3), col = (:red,:green,:blue))

(pos = (2, 3), col = (:red, :green, :blue))

In [620]:
t4[1], t4.pos

((2, 3), (2, 3))

In [621]:
t4[2],t4.col

((:red, :green, :blue), (:red, :green, :blue))

### Arrays
An array can be $n$-dimensional.

A one-dimensional array, also known as a *vector*, or a list, consist of a sequence of elements within square brackets, `[element1, element 2, ..., elementn]`. The elements can be of any type, but will given a common type which is the smallest common denominator in the type hierarchy. The most general type is `Any`.

For higher order arrays, the elements must be of the same type. A two-dimensional array, also known as a *matrix*, consists of row elements separated by *space*, and rows separated by semicolon or linefeed. If the matrix elements are of different type, but are subtypes of the same supertype, they will be converted to a common type.

In [464]:
vec = [1, 1.2e3,"Romeo and Juliet"]

3-element Vector{Any}:
    1
 1200.0
     "Romeo and Juliet"

In [622]:
mat = [1 2e3;2 5]    # all elements are subtypes of `Number`, but they 
                     # are upgraded to `Float64`

2×2 Matrix{Float64}:
 1.0  2000.0
 2.0     5.0

In [623]:
mat = [1 2e3
2 5]

2×2 Matrix{Float64}:
 1.0  2000.0
 2.0     5.0

In [624]:
mat = [1 3; 2+3im -1]    # Here, all elements are upgraded to complex numbers
                         # with `Int64` elements

2×2 Matrix{Complex{Int64}}:
 1+0im   3+0im
 2+3im  -1+0im

In [625]:
mat = [1 pi; 2+3im -1]    # Here, all elements are upgraded to complex numbers
                          # with `Float64` elements

2×2 Matrix{ComplexF64}:
 1.0+0.0im  3.14159+0.0im
 2.0+3.0im     -1.0+0.0im

### Array creation
A number of functions exist for creating arrays
* **Array constructor** `Array{T}(undef,dims)` where `T` is the chosen *data type*, `undef` specifies the elements values, and `dims` is a tuple of sizes in each dimentions, or `dims` can be a comma separated sequence of sizes. When the array content is specified as `undef`, the array is populated with the current value in the relevant memory cells.
* **Alternative fill elements** Alternatively, the fill elements can be value `nothing` which is of datatype `Nothing`, or value `missing` which is of datatype `Missing` - provided that the datatype `T` supports these values. Simple datatypes do *not* support `nothing` or `missing` To get around this, we may create a *union* data type using syntax `Union{T1,T2}`, e.g., `Union{Int64,Missing}`.
* **Vector constructor** `Vector{T}(undef,dim)` where `dim` is a non-negative integer is simply an alias for `Array{T}(undef,dim)`. Alternative filling elements instead of `undef` can be used, just as for the `Array` constructor.
* **Matrix onstructor** `Matrix{T}(undef,dim1,dim2)` where `dim1` and `dim2` are non-negative ingers is an alias for `Array{T}(undef,dim1,dim2)`

The reason why the datatype must be specified as above, is that when we creat arrays from scratch, Julia can not infer what datatype we have in mind.

Some other constructors include information about the fill elements, and then we do not need to specify the type.

* **Zero array** `zeros([T=Float64,] dims)` results in an array of zero elements. The default datatype is `Float64`; specifying the datatype is optional, while the dimensions are given by either a tuple of integers or a sequence of comma separated integers.

* **Unit array** `ones([T=Float64,] dims)` results in an array of unit elements. The default datatype is `Float64`; specifying the datatype is optional, while the dimensions are given by either a tuple of integers or a sequence of comma separated integers.

* **False array** `falses(dims)` results in an array of false elements. The dimensions are given by either a tuple of integers or a sequence of comma separated integers. 

* **True array** `trues(dims)` results in an array of true elements. The dimensions are given by either a tuple of integers or a sequence of comma separated integers. 

* **Fill array** `fill(x,dims)` results in an array of elements with value `x`. The dimensions are given by either a tuple of integers or a sequence of comma separated integers. *Alternatively*, if we already have an array `A`, then `fill!(A,x)` inserts value `x` into the elements. *Note*: for `fill!(A,x)` it is required that the datatype of `x` is the same as that of `A`, or that it can be converted to the datatype of `A` without loss of accuracy -- e.g., if the datatype of `A` is an integer, and `x` is a floating point number, this works if the value of `x` is an integral number.

* **Convert iterator or collection to array** `collect(col)` where `col` is an iterator or collection.

* **Random array** `rand([C,] dims)` creates an array of dimensions `dims` (tuple, or comma separated list of sizes) with random elements. Without specifying optional `C`, elements are random numbers from a uniform distribution on $[0,1)$. With given collection or iterator `C`, the elements are taken randomly from `C`. `randn(dims)` fills the elements with random numbers from a standard normal distribution $\cal{N}(0,1)$.


In [469]:
Array{Int64}(undef,2,3)

2×3 Matrix{Int64}:
 47244640260  64424509446  8589934608
 60129542156   8589934594  4294967298

In [470]:
Array{Union{Int64,Nothing}}(nothing,2,3)

2×3 Matrix{Union{Nothing, Int64}}:
 nothing  nothing  nothing
 nothing  nothing  nothing

In [471]:
Vector{Int64}(undef,2)

2-element Vector{Int64}:
 2413965848032
 2413965169120

In [472]:
zeros(2)

2-element Vector{Float64}:
 0.0
 0.0

In [473]:
zeros(Int16,2)

2-element Vector{Int16}:
 0
 0

In [474]:
ones(Int16,2,3)

2×3 Matrix{Int16}:
 1  1  1
 1  1  1

In [475]:
falses(2,3)

2×3 BitMatrix:
 0  0  0
 0  0  0

In [476]:
mat = trues(2,3)

2×3 BitMatrix:
 1  1  1
 1  1  1

In [477]:
sizeof(mat)

8

In [478]:
fill(2,2,3)

2×3 Matrix{Int64}:
 2  2  2
 2  2  2

In [479]:
fill(Int16(1),2,3)

2×3 Matrix{Int16}:
 1  1  1
 1  1  1

In [480]:
mat = fill(true,2,3)    # Observe that this results in a Matrix of Bool elements

2×3 Matrix{Bool}:
 1  1  1
 1  1  1

In [481]:
sizeof(mat)

6

In [482]:
mat = Matrix{Int16}(undef,2,3)

2×3 Matrix{Int16}:
 0  0   11231
 0  0  -23430

In [483]:
fill!(mat,3)

2×3 Matrix{Int16}:
 3  3  3
 3  3  3

In [484]:
collect(1:3)

3-element Vector{Int64}:
 1
 2
 3

In [485]:
collect((1,2,3))

3-element Vector{Int64}:
 1
 2
 3

In [486]:
rand(2,3)

2×3 Matrix{Float64}:
 0.668002  0.365705  0.689729
 0.78678   0.895477  0.0438605

In [487]:
rand(0:2:5,2,3)

2×3 Matrix{Int64}:
 2  2  0
 0  4  2

In [488]:
rand([:red,:green,:blue],2,3)

2×3 Matrix{Symbol}:
 :red    :red    :blue
 :green  :green  :red

In [489]:
randn(2,3)

2×3 Matrix{Float64}:
 -0.84402   -1.13796   -1.64579
 -0.783681   0.982361  -0.0699268

### Array size and indexing
...ndims(), size(), indices, cartesian indices, etc.
* **Array dimension** `ndims(array)` gives the number of dimensions of `array`.
* **Array size** `size(array)` returns a tuple of the sizes in each dimension. `size(array,dim)` gives the size in dimension `dim`.
* **Array length** `length(array)` returns the product of the elements of the tuple `size(array)`.
* **Cartesian indexing** `array[n1,..,nend]` (`nend` is the same as `ndims(array)`) picks out element `(n1,...,nend)`.
* **Linear indexing** `array[n]` utilizes that Julia uses column-major ordering, i.e., in a matrix, the elements are stored in memory with the first column first, followed by the second column, etc. `array[n]` then picks out its element according to this column-major ordering.
* **Cartesian to linear indexing** `i = CartesianIndex(j,k,...)` gives a single the linear index `i` for cartesian indices `j,k,...`; `I = CartesianIndices(A)` provides an *array* of the same shape as `A` containing its cartesian indices. 
* **Subarray** `array[idx1,...,idxend]` where `idx1,...,idxend` each are iterators or vectors, picks out the relevant subarray. For indices, `:` implies all elements in the particular dimension. 
* **Conversion to vector** `array[:]` converts the array to a vector, using Julia's default column-major ordering.
* **Reshaping arrays** `reshape(array,dims)` converts `array` to a vector, and builds it up column-major wise to a new array of dimensions given by `dims` (tuple, or comma-separated list of integers). It is required that `length(array)` equals the product of elemens in `dims`.
* **Permute dimensions** `permutedims(array,perm)` permutes the dimensions of `array`, where `perm` is a vector of length `ndims(array)`. If `array` is a matrix, the simplified notation `permutedims(array)` swaps the rows and columns, i.e., just like transposition of a matrix. If `array` is a vector, `permutedims(array)` creates a row matrix.

In [490]:
A = Matrix{Int16}(undef,2,3)

2×3 Matrix{Int16}:
   9184  32760  0
 -32694      0  0

In [491]:
ndims(A)

2

In [492]:
size(A), size(A,2)

((2, 3), 3)

In [493]:
length(A), sizeof(A)    #

(6, 12)

In [494]:
mat = rand(0:9,3,4)

3×4 Matrix{Int64}:
 5  5  2  9
 6  5  7  4
 7  5  8  2

In [495]:
mat[2,3]

7

In [496]:
mat[8]

7

In [497]:
i_m = CartesianIndex(2,3)

CartesianIndex(2, 3)

In [498]:
mat[i_m]

7

In [499]:
I_m = CartesianIndices(mat)

CartesianIndices((3, 4))

In [500]:
mat

3×4 Matrix{Int64}:
 5  5  2  9
 6  5  7  4
 7  5  8  2

In [501]:
mat[1:2,1:2]

2×2 Matrix{Int64}:
 5  5
 6  5

In [502]:
mat[1:2,2:-1:1]

2×2 Matrix{Int64}:
 5  5
 5  6

In [503]:
mat[[1,3],[2,4,1]]

2×3 Matrix{Int64}:
 5  9  5
 5  2  7

In [504]:
mat[2:3,:]

2×4 Matrix{Int64}:
 6  5  7  4
 7  5  8  2

In [505]:
mat[2:3,:][:]

8-element Vector{Int64}:
 6
 7
 5
 5
 7
 8
 4
 2

In [506]:
length(mat)

12

In [507]:
reshape(mat,2,6)

2×6 Matrix{Int64}:
 5  7  5  2  8  4
 6  5  5  7  9  2

In [508]:
mat

3×4 Matrix{Int64}:
 5  5  2  9
 6  5  7  4
 7  5  8  2

In [509]:
permutedims(mat)

4×3 Matrix{Int64}:
 5  6  7
 5  5  5
 2  7  8
 9  4  2

In [510]:
permutedims([1,2,3])

1×3 Matrix{Int64}:
 1  2  3

### Array operations
The standard scalar operators (`+`) and subtraction (`-`) works on arrays provided the arrays have identical size and shape; in that case, the operations work element-wise. Array operations multiplication (`*`), division (`/`), power (`^`) do not work in general.

A general design of Julia is that *functions* of scalar argument(s) are mapped to each element by a so-called "dot notation". Thus, if `f()` is a function on a scalar argument, then `f.(array)` maps that operation on every element in the array. For functions with more than one argument, special *broadcasting* operations may be needed if the two arguments have different size/shape. As an example: if we want to add a scalar `1` to an *array*, the language must know what is meant. Typically, before elementwise addition, the scalar `1` is augmented to an array of unit elements of the same size as the array argument. This procedure of adjusting arguments to compatible types in a logical way is what is meant by broadcasting.

Note that for infix operators, the `.` notation comes in *front* of the operator, while for functions in general, the `.` notation comes *after* the function name.

To this end: Julia provides element-by-element standard operations (with possibly broadcasting) for:
* **Addition**: `A .+ B`
* **Subtraction**: `A .- B`
* **Multiplication**: `A .* B`
* **Division**: `A ./ B`, `A .\ B`
* **Power**: `A .^ B`
* **Assignment**: `A .= B`

To  avoid misunderstanding the `.` syntax with decimal point, it is important to insert appropriate spacing.

In [511]:
v1 = [1,2,3]
v2 = [2,3,4]
v1+v2

3-element Vector{Int64}:
 3
 5
 7

In [512]:
v3 = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [513]:
v1[:] + v3[:]    # Here, v1+v3 doesn't work because arrays v1 and v3 have 
                 # different organization/structure (vector vs. row matrix)

3-element Vector{Int64}:
 2
 4
 6

In [514]:
v1 .+ v2

3-element Vector{Int64}:
 3
 5
 7

In [515]:
v1 .+ v3    # Here, broadcasting dictates that `v1` is upgraded to a matrix, 
            # and it is interpreted as a column matrix with value v1[1] in 
            # the first row, v1[2] in the second row, etc. Likewise, `v3`
            # is upgraded to a matrix with the same number of rows as `v1`
            # by copying each row.

3×3 Matrix{Int64}:
 2  3  4
 3  4  5
 4  5  6

In [516]:
A = [1 2; 2 -2]
B = [-1 3; 2 1]
A+B, A.+B

([0 5; 4 -1], [0 5; 4 -1])

In [517]:
A.-B

2×2 Matrix{Int64}:
 2  -1
 0  -3

In [518]:
A.*B

2×2 Matrix{Int64}:
 -1   6
  4  -2

In [519]:
A./B

2×2 Matrix{Float64}:
 -1.0   0.666667
  1.0  -2.0

In [520]:
A.\B

2×2 Matrix{Float64}:
 -1.0   1.5
  1.0  -0.5

In [521]:
A.^B

2×2 Matrix{Int64}:
 1   8
 4  -2

In [522]:
1 .+ A    # Observe that `1.+A` will not work, since this creates uncertainty 
          # whether we mean `1.0 + A` or `1 .+ A`

2×2 Matrix{Int64}:
 2   3
 3  -1

In [523]:
.+(A,B)

2×2 Matrix{Int64}:
 0   5
 4  -1

### Functions applied to arrays

As already mentioned, a general design of Julia is that *functions* of scalar argument(s) are mapped to each element by a so-called "dot notation". Thus, if `f()` is a function on a scalar argument, then `f.(array)` maps that operation on every element in the array. As we will see later, this `.` notation even automatically works on user-defined functions.

For a 1D collection `col` of function arguments, `f(col...)` is a convenient short-hand notation for `f(col[1],...,col[end])`. Operator `...` postpended to a collection (like `col...`) is read *splat* (`col` splat).

These "dot"-operations are *fusing* in the following sense: for combined operations such as `A.^2 + sin.(A)` with `A` an array, this expression will internally be converted into a loop which computes each element `a^2 + sin(a)` independently and *then* puts the result into the result array. Without fusing, one would first compute `A.^2`, create a temporary array for the result, next compute `sin.(A)` and put the result in a temporary array, and finally add these two arrays into a new array. Fusing potentially saves a lot of memory space.

With assignment and fusing, `B = A.^2 + sin.(A)` first creates the array for `A.^2 + sin.(A)`, and then inserts this into array `B`. The alternative, and more efficient method is to write `B .= A.^2 + sin.(A)` -- in this case, the assignment is also fused in the computation, and Julia computes `b = a^2 + sin(a)` in a loop for each element, and avoids temporary array creations.

An alternative to this convenient `.` notation is to use function `map(function,array)`.

In [524]:
A

2×2 Matrix{Int64}:
 1   2
 2  -2

In [525]:
sin.(A)

2×2 Matrix{Float64}:
 0.841471   0.909297
 0.909297  -0.909297

In [526]:
map(sin,A)

2×2 Matrix{Float64}:
 0.841471   0.909297
 0.909297  -0.909297

In [527]:
max([1,-2,2]...)

2

### Selected array functions
* **Accumulation**: `accumulate(op, A; dims::Integer)` computes `A[j] = op(A[1],...,A[j-1])`
* **Cumulative sum**: `cumsum(A; dims::Integer)`
* **Cumulative product**: `cumprod(A; dims::Integer)`
* **Repeating array**: `repeat(A; counts)` where `counts` is a comma separated sequence of integers.
* **Matrix rotation**: `rot180(A)` rotates matrix `A` 180 degrees; `rotl90(A)` rotates a matrix left (counterclockwise) by 90 degrees; `rotl90(A,k)` rotates a matrix left by 90 degress `k` times; `rotr90(A)` rotates a matrix right (clockwise) by 90 degrees; `rotr90(A,k)` rotates a matrix right by 90 degrees `k` times.

In [528]:
v = rand(0:9,4)

4-element Vector{Int64}:
 3
 0
 6
 3

In [529]:
accumulate(+,v)    # With only one dimension, we don't need to specify the dimension

4-element Vector{Int64}:
  3
  3
  9
 12

In [530]:
accumulate(*,v)

4-element Vector{Int64}:
 3
 0
 0
 0

In [531]:
cumsum(v)

4-element Vector{Int64}:
  3
  3
  9
 12

In [532]:
cumprod(v)

4-element Vector{Int64}:
 3
 0
 0
 0

In [533]:
A = rand(0:9,2,3)

2×3 Matrix{Int64}:
 9  3  8
 3  7  8

In [534]:
repeat(A,(2,3)...)   # `(2,3)` is a tuple, and `(2,3)...` is "unpacked" as `2,3`

4×9 Matrix{Int64}:
 9  3  8  9  3  8  9  3  8
 3  7  8  3  7  8  3  7  8
 9  3  8  9  3  8  9  3  8
 3  7  8  3  7  8  3  7  8

In [535]:
rot180(A)

2×3 Matrix{Int64}:
 8  7  3
 8  3  9

In [536]:
rotl90(A,1)

3×2 Matrix{Int64}:
 8  8
 3  7
 9  3

### Array views
A “view” is a data structure that acts like an array, but the underlying data is actually part of another array.
* **Views** `view(array,idx1,...,idxend)`
The purpose of introducing a `view`  is that we can do simpler operations on a subarray *without* creating a new array, and thus *without*  allocating additional memory space.

In [537]:
A = rand(0:9,2,4)

2×4 Matrix{Int64}:
 0  3  7  7
 4  4  2  7

In [538]:
B = A[:,2:3]    # This creates a new array B, and allocates memory for it

2×2 Matrix{Int64}:
 3  7
 4  2

In [539]:
C = view(A,:,2:3)    # This creates a *view* into a submatrix of A, and 
                     # the only additionally allocated memory is the pointer 
                     # to C

2×2 view(::Matrix{Int64}, :, 2:3) with eltype Int64:
 3  7
 4  2

In [540]:
B = 2B

2×2 Matrix{Int64}:
 6  14
 8   4

In [541]:
A

2×4 Matrix{Int64}:
 0  3  7  7
 4  4  2  7

In [542]:
C = 2*C    # With this assignment, `C` is changed, but `A` is not changed --
           # even when `C` is originally a view into `A`. Instead, 
           # the `=` assignment creates a new array `C`.

2×2 Matrix{Int64}:
 6  14
 8   4

In [543]:
A

2×4 Matrix{Int64}:
 0  3  7  7
 4  4  2  7

In [544]:
C = view(A,:,2:3)

2×2 view(::Matrix{Int64}, :, 2:3) with eltype Int64:
 3  7
 4  2

In [545]:
C .= 2*C    # With dot-assignment `.=`, `C` is changed, and so is `A`.

2×2 view(::Matrix{Int64}, :, 2:3) with eltype Int64:
 6  14
 8   4

In [546]:
A

2×4 Matrix{Int64}:
 0  6  14  7
 4  8   4  7

### Concatenation
* **General concatenation**: `cat(A1,...,An; dims)`
* **Vertical concatenation**: `vcat(A1,...,An)` is shorthand notation for `cat(A1,...,An; dims=1)`
* **Horisontal concatenation**: `hcat(A1,...,An)` is shorthand notation for `cat(A1,...,An; dims=2)`
* **Convert vector-of-vector to flat array**: `reduce(vcat/hcat,vec_vec)` is an extremely efficient way to convert a vector-of-vectors to a vector or matrix. Function `reduce` has other uses, too.

In [547]:
v1 = rand(0:9,3)
v2 = rand(0:9,3)
#
v1,v2

([7, 1, 3], [1, 2, 6])

In [548]:
cat(v1,v2;dims=2)    # 1D arrays (vectors) are considered column vectors 
                     # when concatenated

3×2 Matrix{Int64}:
 7  1
 1  2
 3  6

In [549]:
cat(v1,v2;dims=1)

6-element Vector{Int64}:
 7
 1
 3
 1
 2
 6

In [550]:
hcat(v1,v2)

3×2 Matrix{Int64}:
 7  1
 1  2
 3  6

In [627]:
vec = [[1,2,3],[2,0,1],[-2,3,1],[0,0,1]]

4-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [2, 0, 1]
 [-2, 3, 1]
 [0, 0, 1]

In [628]:
reduce(hcat,vec)

3×4 Matrix{Int64}:
 1  2  -2  0
 2  0   3  0
 3  1   1  1

In [630]:
reduce(vcat,vec) |> permutedims

1×12 Matrix{Int64}:
 1  2  3  2  0  1  -2  3  1  0  0  1

### Find elements + modify them based on conditions
Suppose we want to find array elements satisfying a conditions. This can be achieved by using relational operators and logical operations in combination with dot-notation. The result is an array with logical values (`0` or `1`), which can be interpreted as an index array of the original array.

Applying this index array on original array then picks out the elements of the array satisfying the conditions (= are `true`), and we can modify the elements using dot-assignment.

In [551]:
A = rand(-9:9,3,5)

3×5 Matrix{Int64}:
  1  3   2   7  1
  1  1   9  -9  6
 -4  3  -3  -6  0

In [552]:
idx = A .< 0

3×5 BitMatrix:
 0  0  0  0  0
 0  0  0  1  0
 1  0  1  1  0

In [553]:
A[idx]

4-element Vector{Int64}:
 -4
 -3
 -9
 -6

In [554]:
A[idx] .= 0
A

3×5 Matrix{Int64}:
 1  3  2  7  1
 1  1  9  0  6
 0  3  0  0  0

## Dictionaries
Dictionaries are somewhat similar to named tuples: dictionaries are indexed by unique keys, which have specified values.

### Constructor
* `Dict(vec)` where `vec` is a vector of pairs (tuples) of key and value, e.g., `Dict([(key1,val1), (key2,val2), ..., (keyn,valn)]). Keys can not be identifiers, because identifiers are assumed to have a value. But keys can be a number, a Char value, a String, a Symbol, etc.
* `Dict(key1 => val1, key2 => val2, ..., keyn => valn)` is an alternative syntax

It is possible to create an empty dictionary with restrictions on the type of keys and values by `Dict{K,V}()` where `K` is the type of the keys, and `V` is the type of the values.

In [555]:
d1 = Dict([(Symbol("v [m/s]"),1),(:b,2),("c",:b),(1,24)])

Dict{Any, Any} with 4 entries:
  :b                => 2
  "c"               => :b
  Symbol("v [m/s]") => 1
  1                 => 24

### Dictionary functions
* **Has key?**: `haskey(d,k)` where `d` is a dictionary and `k` is a key, returns `true` if dictionary `d` has key `k`.
* **Keys**: `keys(d)` returns an key set for dictionary `d`. The key set can be converted to an array by `collect()`, and then elements may be extracted. 
* **Values**: `values(d)` returns an iterator for the values of `d`. The value iterator can be converted to an array by `collect()`, and then elements may be extracted.
* **Merge**: `merge(d1,...,dn)` returns a merged dictionary from the original dictionaries. If some of the dictionaries have the same key, then result is the right-most dictionary in the merge sequence.

In [556]:
d1[:b]

2

In [557]:
k1 = keys(d1)

KeySet for a Dict{Any, Any} with 4 entries. Keys:
  :b
  "c"
  Symbol("v [m/s]")
  1

In [558]:
v1 = values(d1)

ValueIterator for a Dict{Any, Any} with 4 entries. Values:
  2
  :b
  1
  24

In [559]:
collect(k1)[:]

4-element Vector{Any}:
  :b
  "c"
  Symbol("v [m/s]")
 1

In [560]:
haskey(d1,:b)

true

In [561]:
haskey(d1,'c')

false

In [562]:
d1

Dict{Any, Any} with 4 entries:
  :b                => 2
  "c"               => :b
  Symbol("v [m/s]") => 1
  1                 => 24

In [563]:
d2 = Dict(:c=>4,2=>3)

Dict{Any, Int64} with 2 entries:
  2  => 3
  :c => 4

In [564]:
merge(d1,d2)

Dict{Any, Any} with 6 entries:
  :b                => 2
  "c"               => :b
  2                 => 3
  Symbol("v [m/s]") => 1
  :c                => 4
  1                 => 24

In [565]:
d3 = Dict(:b=>4,2=>3)

Dict{Any, Int64} with 2 entries:
  :b => 4
  2  => 3

In [566]:
merge(d1,d3)

Dict{Any, Any} with 5 entries:
  :b                => 4
  "c"               => :b
  2                 => 3
  Symbol("v [m/s]") => 1
  1                 => 24

## Sets
Sets are collections of *unique*  elements, where there in principle is no order among the elements.
### Constructor
* `Set(col)` creates a set from a collection or an iterator

In [567]:
Set("abca")    # Set from string; the result is a set of Char type

Set{Char} with 3 elements:
  'a'
  'c'
  'b'

In [568]:
Set(1:3)    # Set from iterator

Set{Int64} with 3 elements:
  2
  3
  1

In [569]:
Set(rand(-9:9,10))    # Set from array

Set{Int64} with 8 elements:
  4
  2
  -1
  9
  -3
  -2
  -4
  -9

In [570]:
Set((0,1,1,-2,2))    # Set from tuple

Set{Int64} with 4 elements:
  0
  2
  -2
  1

### Set functions
* **Union**: `union(s1,...,sn)` creates the union of sets `s1,...,sn`
* **Intersection**: `intersect(s1,...,sn)` creates the intersection of sets `s1,...,sn`
* **Set difference**: `setdiff(s1,...,sn)` creates the set difference of sets `s1,...,sn`
* **Subset**: `issubset(s1,s2)` creates a boolean variable -- true if every element of `s1` is in `s2`, false otherwise. Alternative syntax: `⊆(s1,s2)`, where `⊆` is `\subseteq + TAB`. If `s1` is an element (not a subset), then `issubset(s1,s2)` has alternative syntax `∈(s1,s2)`. Is *not* subseteq is expressed by `!issubset(s1,s2)` or alternatively `⊈(s1,s2)`, where `⊈` is `\nsubseteq + TAB`.
* **Set equality**: `issetequal(s1,s2)` returns `true` if the two sets `s1` and `s2` are identical, and `false` otherwise. 
* **Disjoint**: `isdisjoint(s1,s2)` returns `true` if the two sets are disjoint, and `false` otherwise.

In [571]:
s1 = Set(rand(-9:9,5))

Set{Int64} with 4 elements:
  7
  -1
  9
  3

In [572]:
s2 = Set(rand(0:2:9,5))

Set{Int64} with 3 elements:
  4
  6
  8

In [573]:
union(s1,s2)    # alternative: ∪(s1,s2), where ∪  is \cup + TAB

Set{Int64} with 7 elements:
  4
  6
  7
  -1
  9
  8
  3

In [574]:
intersect(s1,s2)    # alternative: ∩(s1,s2), where ∩ is \cap + TAB

Set{Int64}()

In [575]:
setdiff(s1,s2)

Set{Int64} with 4 elements:
  7
  -1
  9
  3

In [576]:
issubset(s1,s2)    # alternative: ⊆(s1,s2), where ⊆ is \subseteq + TAB

false

In [577]:
!issubset(s1,s2)

true

In [578]:
⊈(s1,s2)    # ⊈ is \nsubseteq + TAB

true

In [579]:
∈(4,s1)

false

In [580]:
issetequal(s1,s2)

false

In [581]:
isdisjoint(s1,s2)

true

## General mutable collection functions
* **Add elements**: `push!(collection, elements)` modifies the collection (for *array*; for Dictionary, use `merge`). `pushfirst(collection, elements)` inserts the elements at the start of the collection.
* **Insert element**: `insert(v, i, val)` expands vector `v` by one element, inserts value `val` at index `i` in vector `v`, and shifts elements `i:end` one element down. 
* **Remove last element**: `pop!(collection)` removes the last element, and returns the removed value (for *array*). `popfirst!(collection)` removes the first element, and returns the removed value.
* **Remove specified element**: `pop!(collection, key)` removes element `key`, and returns the removed value (for *dictionary*). `popat(collection,i)` removes element `i` and returns the removed element (for *array*). 
* **Delete**: `deleteat!(v, i)` removes element `i` of vector `v`, thereby shortening the vector by 1.
* **Resize**: `resize!(v,n)` resizes vector `v` to have `n` elements. If `n` is shorter than the current length, the `n` first elements are retained. If `n` is longer than the current length, there is no control of what values are filled into `v`.
* **Append**: `append!(col1, ..., coln)` adds collections to (the end of) collection `col1`. `prepend(col1,..., coln)` inserts collections (to the front of) collection `col1`.

In [582]:
a1 = [1,2,3]
push!(a1,3,4)
a1

5-element Vector{Int64}:
 1
 2
 3
 3
 4

In [583]:
pushfirst!(a1,-2,-3)

7-element Vector{Int64}:
 -2
 -3
  1
  2
  3
  3
  4

In [584]:
insert!(a1,3,20)

8-element Vector{Int64}:
 -2
 -3
 20
  1
  2
  3
  3
  4

In [585]:
deleteat!(a1,4)

7-element Vector{Int64}:
 -2
 -3
 20
  2
  3
  3
  4

In [586]:
pop!(a1)

4

In [587]:
a1

6-element Vector{Int64}:
 -2
 -3
 20
  2
  3
  3

In [588]:
popfirst!(a1)

-2

In [589]:
a1

5-element Vector{Int64}:
 -3
 20
  2
  3
  3

In [590]:
d1 = Dict([(:a,7),(:b,[1,2]),("c",[1 2;3 4])])

Dict{Any, Any} with 3 entries:
  :a  => 7
  :b  => [1, 2]
  "c" => [1 2; 3 4]

In [591]:
pop!(d1,:b)

2-element Vector{Int64}:
 1
 2

In [592]:
d1

Dict{Any, Any} with 2 entries:
  :a  => 7
  "c" => [1 2; 3 4]

In [593]:
popat!(a1,2)

20

In [594]:
a1

4-element Vector{Int64}:
 -3
  2
  3
  3

In [595]:
resize!(a1,2)

2-element Vector{Int64}:
 -3
  2

In [596]:
resize!(a1,5)

5-element Vector{Int64}:
 -3
  2
  3
  3
  4

In [597]:
append!(a1,[2,3])

7-element Vector{Int64}:
 -3
  2
  3
  3
  4
  2
  3

In [598]:
prepend!(a1,[-17,-18])

9-element Vector{Int64}:
 -17
 -18
  -3
   2
   3
   3
   4
   2
   3